# .github/workflows/deploy.yml
name: Deploy static content to Pages

on:
  push:
    branches: ["GPU"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write    # for deploy-pages
  id-token: write # not strictly needed here but harmless

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: deploy
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure GitHub Pages site exists
        # Uses your PAT to POST /repos/:owner/:repo/pages
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/pages \
            -d '{"source":{"branch":"GPU","path":"/"}}' \
          || echo "Site likely already exists"

      - name: Package site
        run: |
          tar --dereference --hard-dereference --directory . -cf artifact.tar .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact.tar
          retention-days: 1
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.PAT }}
