name: Deploy static content to Pages
on:
  push:
    branches: ["GPU"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
        
      - name: Package site
        run: |
          # List directory contents before tar
          echo "Directory contents before tar:"
          ls -la
          
          # Create the artifact using tar
          tar --dereference --hard-dereference -cvf artifact.tar .
          
          # Verify the tar file was created
          echo "Checking if artifact.tar was created:"
          ls -la artifact.tar
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact.tar
          retention-days: 1
          if-no-files-found: error
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
