# .github/workflows/deploy.yml
name: Deploy static content to Pages

on:
  push:
    branches: ["GPU"]
  workflow_dispatch:

permissions:
  contents: read     # read your code
  pages: write       # publish to Pages
  id-token: write    # required by configure-pages

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: deploy
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If this is a brand-new repo/site, ensure Pages is enabled:
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          # use PAT only on first run if Pages is disabled; after that you can revert to GITHUB_TOKEN
          token: ${{ secrets.PAT }}
          enablement: github

      # (Optional) build step, if your site uses a static-site generator
      # - name: Build
      #   run: npm ci && npm run build

      # Upload the entire working directory (or your build dir) for Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # point this at your generated site folder; "." if everything’s already in /
          path: .

      # Deploy what you just uploaded
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
        with:
          # you can switch back to GITHUB_TOKEN here once the site exists
          token: ${{ secrets.PAT }}
